// LOGIN
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHANGE_LOGIN_SCREEN = 'CHANGE_LOGIN_SCREEN';

// LIST
export const FETCH_FEE_LIST = 'FETCH_FEE_LIST';
export const FETCH_BRANCH_LIST = 'FETCH_BRANCH_LIST';
export const FETCH_STATUS_LIST = 'FETCH_STATUS_LIST';
export const FETCH_COUNTRY_LIST = 'FETCH_COUNTRY_LIST';
export const FETCH_MANIFEST_LIST = 'FETCH_MANIFEST_LIST';
export const FETCH_CUSTOMER_LIST = 'FETCH_CUSTOMER_LIST';
export const FETCH_IMPORT_MANIFEST_LIST = 'FETCH_IMPORT_MANIFEST_LIST';

// MANIFEST
export const FETCH_MANIFEST = 'FETCH_MANIFEST';
export const SEARCH_MANIFEST = 'SEARCH_MANIFEST';
export const EDIT_MANIFEST = 'EDIT_MANIFEST';

// ORDER
export const FETCH_ORDER = 'FETCH_ORDER';
export const SEARCH_ORDER = 'SEARCH_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';
export const FETCH_ORDER_TRACKING = 'FETCH_ORDER_TRACKING';
export const FETCH_ORDER_TRACKING_COUNT = 'FETCH_ORDER_TRACKING_COUNT';
export const FETCH_ORDER_COUNT = 'FETCH_ORDER_COUNT';
export const FETCH_ORDER_IMPORT = 'FETCH_ORDER_IMPORT';

// CHANGE_PAGE
export const CHANGE_PAGE = 'CHANGE_PAGE';

// DASHBOARD
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';

// CHANGE_LANGUAGE
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';